# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"


# Setup
title:               Panagiotis Kostopanagiotis | Peer to Peer Collaboration and Learning
tagline:             ''
description:         'This is the description'
url:                 http://infinity4471.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Panagiotis Kostopanagiotis
  url:               https://github.com/infinity4471
  email:             panagiotis.kostopanagiotis@gmail.com

# Custom vars
version:             1.0.0
